# Generated by Django 3.1 on 2020-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200823_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FilePathField(path='/static/img/'),
        ),
    ]
