# Generated by Django 3.1 on 2020-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200824_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FilePathField(path='~/mnt/c/Users/91894/desktop/SHOP-PY/Shop-py/WebApp/static/img/'),
        ),
    ]
