# Generated by Django 3.1 on 2020-08-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200825_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.FilePathField(path='img/'),
        ),
    ]
